### ISSUE TITLE
Use of the session present flag

### ISSUE THREAD

**Issue by trustefda** [LiamBindle/MQTT-C#36] opened 2019-04-10 08:39 UTC
First of all thanks for the successful MQTT library for embedded systems.

I have the request to evaluate the session present flag from the CONNACK packet. If the flag is not set, my application must re-subscribe to the topics. If the flag is set my application may not subscribe to the topics again.

How would you implement that? I would suggest to specify another callback function during initialization. This is called when a **new session** has been established. The callback function can then ask the application to subscribe to the topics.

**Comment by LiamBindle** [comment] 2019-04-10 22:19
Hi Stefan,

I took a quick look at the "Session Present" flag (Section 3.2.2.2 of the [MQTT v3.1.1 standard](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Figure_3.8_%E2%80%93) for reference) and I don't really understand what it is supposed to do. 

Is the idea just that you don't have to resend all the SUBSCRIBE packets? If so, why is this a problem (since these are all small packets anyways)? I'm don't understand what the expected behaviour of the "Session Present" flag is.

Cheers,

Liam

**Comment by trustefda** [comment] 2019-04-11 05:15
Hi Liam,

right. One issue is that the client does not have to subscribe to the topics again. For extremely poorly connected clients, that could be interesting. But there are other aspects. In the following I quote from https://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages/

**Persistent Session**

- The client must get all messages from a certain topic, even if it is offline. You want the broker to queue the messages for the client and deliver them as soon as the client is back online.
- The client has limited resources. You want the broker to store the subscription information of the client and restore the interrupted communication quickly.
- The client needs to resume all QoS 1 and 2 publish messages after a reconnect.

**Comment by LiamBindle** [comment] 2019-04-12 13:42
Oh, I see what you mean. Let's continue our discussion of #11 here as well. Also, sorry, I didn't realize you were looking for how to get started on implementing this&mdash;that's great! Let me know when you run into problems, and I'm happy to merge in your pull requests.

The big thing to keep in mind when you're working on this, and resending unacknowledged messages upon a reconnect is that **MQTT-C does not use any dynamic memory allocation**.

Thoughts on implementing the "Session Present" flag:
- Add a flag to `struct mqtt_client` that tracks the value of "Session Present" 
- In `mqtt_connect` set the proper bit in the header equal to the value of the "Session Present" flag
- Rely on the user-implemented `reconnect_callback` to properly set this flag.

If the server's response doesn't recognize the session is present (or the server doesn't support this) then I see two options:
1. Throw a fatal `MQTT_ERROR`. You'll need to make add a new error to the enum of errors.
2. Implement some functionality to call `mqtt_subscribe` for a list of topics that you'll need to track (e.g. an array of c-string with topic names that is updated by `mqtt_subscribe` and `mqtt_unsubscribe`.

Throughts on implementing resending of unacknowledge packets after a reconnect:
1. You're going to need to have the "Session Present" flag implemented.
2. You'll have to add some functionality to `mqtt_message_queue` so that messages can be *inserted at the front of the message queue*. Then in `mqtt_reinit` rather then calling `mqtt_mq_init` ([line 167](https://github.com/LiamBindle/MQTT-C/blob/f4fcafeb0398572d6aa8613b76f4fe21f0de87ee/src/mqtt.c#L167); responsible for deleting all messages in the message queue), you'll want to switch on the "insert at the front" functionality before calling the users reconnect callback.

Let me know if you need clarification on anything.

**Comment by LiamBindle** [comment] 2019-05-01 13:35
Hi @trustefda,

I'm going to assume I can close this issue.

Feel free to reopen it if you'd like.

Cheers,

Liam

**Closed by LiamBindle** 2019-05-01 13:35 UTC
Labels: enhancement
