### ISSUE TITLE
Example payload contains unwanted charactors 

### ISSUE THREAD

**Issue by wyx087** [LiamBindle/MQTT-C#68] opened 2020-02-13 09:15 UTC
In your subscriber examples, directly printing `(const char*) published->application_message` occasionally gives extra unwanted charactors. This makes number-based payload unreliable and introduces errors into calculations. 

To fix this, I've added usage of application_message_size in the printf statement. For example: 
`sprintf(payload, "%.*s", published->application_message_size, (const char*) published->application_message);`

**Comment by LiamBindle** [comment] 2020-02-13 20:04
@wyx087 Thanks for raising the issue. The examples are just meant to be simple demos of how to get started, but I wasn't aware the subscriber gives extra characters some times&mdash;do you know why? To me it looks like the null-character should be included in the payload:
https://github.com/LiamBindle/MQTT-C/blob/399361fb011577bf7c0444a08982a18a739f91fd/examples/simple_publisher.c#L118

**Comment by learn-more** [comment] 2020-02-13 20:17
The problem is most likely that not all publishers do this.
The default samples continue sessions from others, so he might be looking at that

**Comment by LiamBindle** [comment] 2020-02-13 20:25
That's a good point. @wyx087 did you modify simple_publisher.c? If you're using simple_subscriber.c out-of-the-box on a common testing broker like https://test.mosquitto.org, the topic name is "datetime" so it's possible other peoples' publishes to "datetime" are coming back to you.

Regardless, I don't think this is a bug, but @wyx087 your approach using `application_message_size` is what you should be doing.

I'm going to close this issue but feel free to reopen

**Closed by LiamBindle** 2020-02-13 20:25 UTC

**Comment by wyx087** [comment] 2020-02-13 20:52
I agree, it's not a bug for the core program. The purpose of this post is just to make you aware that the examples could use some form of length limiter. Hopefully will save other novices like me from some head-scratching. 

Quite possibly the problem lies with my publisher. But monitoring with Home Assistant MQTT doesn't reproduce this. Equally, HA could have implemented length limiter. 

Here is debug output from my program, which is adopted from your reconnect_subscriber example. 
Publisher is https://github.com/emoncms/emoncms
First print shows message as shown by your example. Second print uses the sprintf I posted earlier. 
```
Received publish('power/export'): 06.74power/usage226.74power/usage227.22
Received publish('power/export'): '0'
Received publish('power/solar'): -00
Received publish('power/solar'): '-0'
Received publish('power/usage'): 228.86power/usage228.86power/usage227.22
Received publish('power/usage'): '228.86'

Received publish('power/export'): 06.86power/usage206.86power/usage206.86
Received publish('power/export'): '0'
Received publish('power/solar'): -00
Received publish('power/solar'): '-0'
Received publish('power/usage'): 207.8
                                      power/usage207.86power/usage206.86
Received publish('power/usage'): '207.8'
```
This was recorded at nearly 9pm, export value should be solid 0. The 06.74 value throws off some calculations I do later.
